[goldmark]
[goldmark.extensions]
table = true
[goldmark.extensions.passthrough]
enable = false
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]


[goldmark.renderer]
# This setting allows inlining <script> and <style> tags in markdown,
# which is useful and required to use Prism plugins, but may be dangerous
# if the content isn't trustworthy.
unsafe = true


[goldmark.parser]
[goldmark.parser.attribute]
block = true
